# Ch2 序列构成的数组

## 2.1 内置序列类型概览

容器序列
- `list`, `tuple`, `collections.deque` 可存放不同类型的数据

扁平序列
- `str`, `bytes`, `bytearray`, `memoryview`, `array.array` 只能容纳一种类型

容器序列存放的是引用，而扁平序列存放的是值。扁平序列是一段连续的内存空间。

可变序列
- `list`, `bytearray`, `array.array`, `collections.deque`, `memoryview`

不可变序列
- `tuple`, `str`, `bytes`

可变序列从不可变序列处继承了一些方法

继承树如下:

`Container`类
- `__contains__`

`Iterable`类
- `__iter__`

`Sized`类
- `__len__`

`Sequence`类 extends `Container`, `Iterable`, `Sized`
- `__getitem__`
- `__contains__`
- `__iter__`
- `__reversed__`
- `index`
- `count`

`MutableSequence`类 extends `Sequence`
- `__setitem__`
- `__delitem__`
- `insert`
- `append`
- `reverse`
- `extend`
- `pop`
- `remove`
- `__iadd__`


## 2.2 列表推导和生成器表达式
通常的原则是，只用列表推导来创建新的列表，并且尽量保持简短。超过了两行的话，就要考虑是不是应该用for循环重写。

In [40]:
symbols = '$¢£¥€¤'
beyond_ascii = [ord(s) for s in symbols if ord(s) > 127]
print(beyond_ascii)

[162, 163, 165, 8364, 164]


In [41]:
# or using map/filter
beyond_ascii = list(filter(lambda c : c > 127, map(ord, symbols)))
print(beyond_ascii)

[162, 163, 165, 8364, 164]


Comparison of speed can be found in *listcomp_speed.py*

### 2.2.3 cartesian product

In [42]:
colors = ['black', 'white'] 
sizes = ['S', 'M', 'L'] 
tshirts = [(color, size) for color in colors for size in sizes]
print(tshirts)

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]


### 2.2.4 生成器表达式
生成器表达式是懒惰的，只有在需要的时候才会生成值,这样有助于节省内存。生成器表达式的语法和列表推导很像，只不过把中括号换成了圆括号。

In [43]:
tuple(ord(symbol) for symbol in symbols)

(36, 162, 163, 165, 8364, 164)

In [44]:
import array
arr = array.array('I', (ord(symbol) for symbol in symbols))
print(arr)


array('I', [36, 162, 163, 165, 8364, 164])


1. 如果生成器表达式是一个函数调用过程中的唯一参数，那么不需要额外的括号
2. array的构造方法需要两个参数，第一个指定了数组中数字的储存方式，第二个是可迭代对象

In [45]:
colors = ['black','white']
sizes = ['S','M','L']
for tshirt in ('%s %s' % (c,s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


## 2.3 元组不仅仅是不可变的列表
除了用作不可变的列表，它还可以用于没有字段名的记录

### 2.3.1 元组和记录

如果只把元组理解为不可变的列表，那其他信息——它所含有的元素的总数和它们的位置——似乎就变得可有可无。但是如果把元组当作一些字段的集合，那么**数量和位置信息**就变得非常重要了。

### 2.3.2 元组拆包
可以参考Python Techniques系列的笔记


In [46]:
# * unpacks an iterable
t = (20,8)
print(divmod(*t))

(2, 4)


parallel assignment technique

In [47]:
a, *body, c, d = range(5)
print(a,body,c,d)

0 [1, 2] 3 4


### 2.3.3 嵌套元组拆包
接受表达式的元组可以是嵌套式的，例如(a, b, (c, d))。

In [48]:
# metro_lat_long.py
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35.689722, 139.691667)),   # <1>
    ('Delhi NCR', 'IN', 21.935, (28.613889, 77.208889)),
    ('Mexico City', 'MX', 20.142, (19.433333, -99.133333)),
    ('New York-Newark', 'US', 20.104, (40.808611, -74.020386)),
    ('Sao Paulo', 'BR', 19.649, (-23.547778, -46.635833)),
]

print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:  # <2>
    if longitude <= 0:  # <3>
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.4333 |  -99.1333
New York-Newark |   40.8086 |  -74.0204
Sao Paulo       |  -23.5478 |  -46.6358


### 2.3.4 具名元组(namedtuple)
collections.namedtuple是一个**工厂函数**，它可以用来构建一个带字段名的元组和一个有名字的类——这个带名字的类对调试程序有很大帮助。

*拓展:工厂函数*

In programming, a factory function is a concept used primarily in object-oriented programming. It refers to a function that is designed to create and return new instances of objects. Unlike constructors that are associated with a specific class and are used to create instances of that class, factory functions can be more flexible. They can create objects from multiple classes based on the parameters passed to them or based on specific conditions.

Factory functions are useful for several reasons:
1. **Abstraction and Encapsulation**: They can hide the complexity of creating instances of complex objects, making the code that uses these objects simpler and cleaner.
2. **Flexibility**: Since factory functions are not tied to specific classes, they can return instances of different classes. This makes it easier to introduce new types of objects without changing the code that uses the factory function.
3. **Customization**: Parameters passed to a factory function can dictate the customization of the created object, allowing for a more dynamic object creation process.

Here's a simple example in JavaScript to illustrate a factory function:

```javascript
function carFactory(model, year) {
    return {
        model: model,
        year: year,
        displayInfo: function() {
            console.log(`Model: ${this.model}, Year: ${this.year}`);
        }
    };
}

const car1 = carFactory('Toyota', 2020);
car1.displayInfo(); // Output: Model: Toyota, Year: 2020
```

In this example, `carFactory` is a factory function that creates and returns a new car object each time it is called. The created car object includes properties for `model` and `year`, as well as a method `displayInfo` to display the car's information. This approach allows for the creation of car objects with different properties without the need for a specific class for each car.

书本注:
用`namedtuple`构建的类的实例所消耗的内存和元组一样，因为字段名都被存在对应的类内。这个实例比普通的对象实例比起来要小一点，因为python不会用`__dict__`来存放这些实例的属性

In [49]:
from collections import namedtuple
City = namedtuple('City','name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689722, 139.691667))

In [50]:
print(tokyo)
print(tokyo.name)
print(tokyo.population)

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689722, 139.691667))
Tokyo
36.933


*code comment:*
1. 创建`namedtuple`需要两个参数，一个是类名，另一个是类的各个字段的名字。后者可以是由数个**字符串组成的可迭代对象**，或者是由**空格分隔开的字段名组成的字符串**。
2. 存放在对应字段里的数据要以一串参数的形式传入到构造函数中（元组的构造函数却只接受单一的可迭代对象）
3. ...

具名元组还有一些自己专有的属性:
- `_fields` class attribute
- `_make(iterable)` class method
- `_asdict()` instance method

In [51]:
City._fields

('name', 'country', 'population', 'coordinates')

In [52]:
LatLong = namedtuple('LatLong', 'lat long') 
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613889, 77.208889)) 
delhi = City._make(delhi_data)   
print(delhi._asdict()) 

{'name': 'Delhi NCR', 'country': 'IN', 'population': 21.935, 'coordinates': LatLong(lat=28.613889, long=77.208889)}


In [53]:
for key, value in delhi._asdict().items(): 
    print(key + ':', value) 

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613889, long=77.208889)


*code comment:*
1. `_fields`属性是一个包含这个类所有字段名称的元组。
2. 用`_make()`通过接受一个可迭代对象来生成这个类的一个实例，它的作用跟`City(*delhi_data)`是一样的。
3. `_asdict()`把具名元组以`collections.OrderedDict`的形式返回，我们可以利用它来把元组里的信息清晰的呈现出来。

### 2.3.5 作为不可变列表的元组

除了和增减元素相关的方法之外，元组支持列表的其他所有方法。有一个例外是元组没有`__reversed__`方法 (书上描述:这个方法只是个优化) ，但是可以使用`reversed()`函数。

注: `__reversed__` method returns an iterator of reversed items

In [54]:
a = (1,2,3)
a = reversed(a)
print(a)
print(tuple(a))

(3, 2, 1)


In [55]:
a = [1,2,3]
a = reversed(a)
print(a)
print(list(a))

[3, 2, 1]


## 2.4 切片
`a:b:c` 这种用法只能作为索引或者下标用在[]中来返回一个切片对象：`slice(a, b, c)` 。对`seq[start:stop:step]` 进行求值的时候，Python会调用`seq`. 
`__getitem__(slice(start, stop, step))`。

(may refer to a video about slicing <a href = "https://www.bilibili.com/video/BV1ki421v7Ao/?share_source=copy_web&vd_source=0f2805b5dbbfea4fe3a5cd27c708c741">【Python】Slice：被低估的小技巧，减少重复工作量 </a>)

### 2.4.3 多维切片和省略
`[]` 运算符里还可以使用以逗号分开的多个索引或者是切片, numpy库就利用了这个特性。

要正确处理这种`[]`运算符的话，对象的特殊方法`__getitem__`和`__setitem__`需要以元组的形式来接收`a[i, j]`中的索引。也就是说，如果要得到`a[i, j]`的值，Python会调用`a.__getitem__((i, j))`

省略`...`是Ellipsis对象的别名，它可以表示任意多的冒号

书本注：fun fact, `Ellipsis` object is a singleton object of `ellipsis` class (Ellipsis是一个内置实例). Yes, it is a class with lower letters. Similar to `bool` class with `True` and `False` instances.


In [56]:
import numpy as np

a = np.array([[[[1,2,3,4],[5,6,7,8]],[[12,34,56,78],[56,78,90,12]]],[[[1,2,3,4],[5,6,7,8]],[[12,34,56,78],[56,78,90,12]]]])
b = a[0, ...] # very interesting example
print(b)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[12 34 56 78]
  [56 78 90 12]]]


### 2.4.4 给切片赋值（有意思）
如果把切片放在赋值语句的左边，或把它作为`del`操作的对象，我们就可以对序列进行**嫁接、切除或就地修改**操作。

In [57]:
l = list(range(10))
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [58]:
l[2:5] = [20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [59]:
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [60]:
l[3::2] = [11,22]
l

[0, 1, 20, 11, 5, 22, 9]

In [61]:
# l[2:5] = 100 error because 100 is not iterable
l[2:5] = [100] 
l

[0, 1, 100, 22, 9]

如果赋值的对象是一个切片，那么赋值语句的右侧**必须是个可迭代对象**。即便只有单独一个值，也要把它转换成可迭代的序列。

## 对序列使用`+`和`*`
`+`和`*`都遵循这样的规律：不修改原有的操作对象，而是构建一个全新的序列。

`*`操作符的一个潜在的缺点是，它会把一个单一的元素复制多次以构建新的列表。这意味着，如果这个元素是**可变的**，就可能导致意想不到的副作用。(萌新时期噩梦!)

以下是一些正确/错误的用法！
最正确的方式是listcomp！

In [62]:
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [63]:
board[1][2] = 'X'
board

[['_', '_', '_'], ['_', '_', 'X'], ['_', '_', '_']]

In [64]:
weird_board = [['_'] * 3] * 3
weird_board[1][2] = 'O'
weird_board

[['_', '_', 'O'], ['_', '_', 'O'], ['_', '_', 'O']]

In [65]:
row=['_'] * 3 
board = [] 
for i in range(3):
    board.append(row)

In [66]:
board = []
for i in range(3):
    row = ['_'] * 3 # creating a new list each iteration
    board.append(row)
board[2][0] = 'X' 
board

[['_', '_', '_'], ['_', '_', '_'], ['X', '_', '_']]

## 2.6 序列的增量赋值
`+=`背后的特殊方法是`__iadd__` (in-place addition)。如果一个类没有实现该方法，Python会后退一步调用`__add__`。变量名会不会被关联到新的对象，完全取决于这个类型有没有实现__iadd__这个方法

In [67]:
l = [1,2,3]
print(id(l))
l *= 2
print(id(l))
t = (1,2,3)
print(id(t))
t *= 2
print(id(t))

3122698992640
3122698992640
3122693751488
3122694482304


In [68]:
# 一个+=的谜题
t = (1,2,[30,40])
print(id(t))
t[2] += [50,60]

3122693751488


TypeError: 'tuple' object does not support item assignment

In [69]:
print(t)
print(id(t))

(1, 2, [30, 40, 50, 60])
3122693751488


In [70]:
import dis # 可以查看python字节码
dis.dis("s[a] += b")

  1           0 LOAD_NAME                0 (s)
              2 LOAD_NAME                1 (a)
              4 DUP_TOP_TWO
              6 BINARY_SUBSCR
              8 LOAD_NAME                2 (b)
             10 INPLACE_ADD
             12 ROT_THREE
             14 STORE_SUBSCR
             16 LOAD_CONST               0 (None)
             18 RETURN_VALUE


## 2.7 list.sort方法和内置函数sorted

与list.sort 相反的是内置函数sorted，它会新建一个列表作为返回值。这个方法可以接受任何形式的可迭代对象作为参数，甚至包括不可变序列或生成器。 but it always returns a list.
...

## 2.8 用bisect来管理已排序的序列
`bisect` 模块包含两个主要函数，`bisect`和`insort`，两个函数都利用二分查找算法来在有序序列中查找或插入元素。


In [71]:
# bisect_demo.py
# BEGIN BISECT_DEMO
import bisect
import sys

HAYSTACK = [1, 4, 5, 6, 8, 12, 15, 20, 21, 23, 23, 26, 29, 30]
NEEDLES = [0, 1, 2, 5, 8, 10, 22, 23, 29, 30, 31]

ROW_FMT = '{0:2d} @ {1:2d}    {2}{0:<2d}'

def demo(bisect_fn):
    for needle in reversed(NEEDLES):
        position = bisect_fn(HAYSTACK, needle)  # <1>
        offset = position * '  |'  # <2>
        print(ROW_FMT.format(needle, position, offset))  # <3>

if __name__ == '__main__':

    if sys.argv[-1] == 'left':    # <4>
        bisect_fn = bisect.bisect_left
    else:
        bisect_fn = bisect.bisect

    print('DEMO:', bisect_fn.__name__)  # <5>
    print('haystack ->', ' '.join('%2d' % n for n in HAYSTACK))
    demo(bisect_fn)

# END BISECT_DEMO


DEMO: bisect_right
haystack ->  1  4  5  6  8 12 15 20 21 23 23 26 29 30
31 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |31
30 @ 14      |  |  |  |  |  |  |  |  |  |  |  |  |  |30
29 @ 13      |  |  |  |  |  |  |  |  |  |  |  |  |29
23 @ 11      |  |  |  |  |  |  |  |  |  |  |23
22 @  9      |  |  |  |  |  |  |  |  |22
10 @  5      |  |  |  |  |10
 8 @  5      |  |  |  |  |8 
 5 @  3      |  |  |5 
 2 @  1      |2 
 1 @  1      |1 
 0 @  0    0 


In [72]:
def grade_right(score, breakpoint = [60,70,80,90], grades = "FDCBA"):
    i = bisect.bisect(breakpoint, score)
    return grades[i]

def grade_left(score, breakpoint = [60,70,80,90], grades = "FDCBA"):
    i = bisect.bisect_left(breakpoint, score)
    return grades[i]

print([grade_right(score) for score in [33,99,77,70,89,90,100]])
print([grade_left(score) for score in [33,99,77,70,89,90,100]])

['F', 'A', 'C', 'C', 'B', 'A', 'A']
['F', 'A', 'C', 'D', 'B', 'B', 'A']


`bisect` can replace `index` in very long sequences to improve efficiency.

### 2.8.2 用`bisect.insort`插入新元素
`bisect.insort` 会找到插入元素的位置并保持序列排序。
Here is an example:

In [73]:
# bisect_insort.py

import bisect
import random

SIZE = 7

random.seed(1729)

my_list = []
for i in range(SIZE):
    new_item = random.randrange(SIZE*2)
    bisect.insort(my_list, new_item)
    print('%2d ->' % new_item, my_list)


10 -> [10]
 0 -> [0, 10]
 6 -> [0, 6, 10]
 8 -> [0, 6, 8, 10]
 7 -> [0, 6, 7, 8, 10]
 2 -> [0, 2, 6, 7, 8, 10]
10 -> [0, 2, 6, 7, 8, 10, 10]


`insort` 跟 `bisect` 一样，有`lo`和`hi`两个可选参数用来控制查找的范围。它也有个变体叫`insort_left`，这个变体在背后用的是`bisect_left`。

# 2.9 当列表不是首选时


比如，要存放1000 万个浮点数的话，数组（array）的效率要高得多，因为数组在背后存的并不是float对象，而是数字的机器翻译，也就是字节表述
`array.tofile()` and `array.fromfile()` can be used to save and load large arrays. And they are really fast!
(similarly, `pickle.dump()` and `pickle.load()` can be used to save and load any object)

In [74]:
from array import array
a = array('b',[2,9,1,5,7])
a = array(a.typecode, sorted(a)) # cannot use list.sort() after Python 3.4

In [75]:
print(a) 

array('b', [1, 2, 5, 7, 9])


### 2.9.2 memory view(?)
memoryview 是一个内置类，它能让用户在不复制内容的情况下操作同一个数组的不同切片。

In [76]:
numbers = array('h',[-2, -1, 0, 1, 2]) # short type
memv = memoryview(numbers)
len(memv)

5

In [77]:
print(memv[0])

-2


In [78]:
memv_oct = memv.cast('B') # cast to unsigned char
memv_oct.tolist()

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [79]:
memv_oct[5] = 4
numbers 

array('h', [-2, -1, 1024, 1, 2])

因为我们把占2个字节的整数的高位字节改成了4，所以这个有符号整数的值就变成了1024

跳过Numpy和Scipy的部分（嘻嘻）

### 双向队列和其他形式的队列

We can use `append` and `pop` to add and remove elements from both ends of a list. But it is not efficient these operations require moving all elements inside the list.

`collections.deque` is a thread-safe double-ended queue designed for fast inserting and removing from both ends. It is also the best choice if you need to keep a list of "last seen items" or something like that (with `deque`).


In [80]:
from collections import deque
dq = deque(range(10), maxlen = 10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [81]:
dq.rotate(3)
dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6], maxlen=10)

In [82]:
dq.rotate(-4)
dq

deque([1, 2, 3, 4, 5, 6, 7, 8, 9, 0], maxlen=10)

In [83]:
dq.appendleft(-1)
dq

deque([-1, 1, 2, 3, 4, 5, 6, 7, 8, 9], maxlen=10)

In [84]:
dq.extend([11,22,33])
dq

deque([3, 4, 5, 6, 7, 8, 9, 11, 22, 33], maxlen=10)

In [85]:
dq.extendleft([10,20,30,40])
dq

deque([40, 30, 20, 10, 3, 4, 5, 6, 7, 8], maxlen=10)

为了实现`popleft`&`rotate`等方法，双向队列也付出了一些代价，从队列中间删除元素的操作会慢一些，因为它只对在头尾的操作进行了优化。

`append`和`popleft`都是原子操作，也就说是`deque`可以在多线程程序中安全地当作先进先出的栈使用，而使用者不需要担心资源锁的问题。

了解：`queue` `multiprocessing` `asyncio` `heapq`也有自己的队列实现（之后可以了解一下用法）

章末杂谈有个有关`key`的例子很有趣

In [86]:
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19] 
sorted(l, key=int)

[0, '1', 5, 6, '9', 14, 19, '23', 28, '28']

In [87]:
l = [28, 14, '28', 5, '9', '1', 0, 6, '23', 19] 
sorted(l, key=str)

[0, '1', 14, 19, '23', 28, '28', 5, 6, '9']

需要决定到底是把字符看作数值，还是把数值看作字符

有关`Timsort`
- sorted 和 list.sort 背后的排序算法是Timsort，它是一种自适应算法，会根据原始数据的顺序特点交替使用插入排序和归并排序，以达到最佳效率。